[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Function proxy must come before SPA fallback
[[redirects]]
  from = "/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/.netlify/functions/status"
  to = "/.netlify/functions/status"
  status = 200

[[redirects]]
  from = "/.netlify/functions/leaderboard"
  to = "/.netlify/functions/leaderboard"
  status = 200

[[redirects]]
  from = "/.netlify/functions/battle-simulate"
  to = "/.netlify/functions/battle-simulate"
  status = 200

[[redirects]]
  from = "/.netlify/functions/battle-validate"
  to = "/.netlify/functions/battle-validate"
  status = 200

[[redirects]]
  from = "/.netlify/functions/health"
  to = "/.netlify/functions/health"
  status = 200

# SPA fallback for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[template.environment]
  HF_MODEL_URL = "https://api-inference.huggingface.co/models/microsoft/DialoGPT-medium"
  HF_API_KEY = ""
  NODE_VERSION = "20"