[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Function proxy must come before SPA fallback
[[redirects]]
  from = "/chat"
  to = "/.netlify/functions/chat"
  status = 200

# SPA fallback for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[template.environment]
  HF_MODEL_URL = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2"
  HF_API_KEY = ""
  NODE_VERSION = "20"